# Generated by Django 3.0.4 on 2020-03-27 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avvik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avvik', models.TextField()),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde', models.CharField(max_length=255)),
                ('kundeinformasjon', models.CharField(blank=True, max_length=255, null=True)),
                ('badresse', models.CharField(blank=True, max_length=255, null=True)),
                ('bpostnr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bpoststed', models.CharField(blank=True, max_length=255, null=True)),
                ('fadresse', models.CharField(blank=True, max_length=255, null=True)),
                ('fpostnr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fpoststed', models.CharField(blank=True, max_length=255, null=True)),
                ('kontaktperson', models.CharField(blank=True, max_length=255, null=True)),
                ('tlf1', models.PositiveIntegerField(blank=True, null=True)),
                ('tlf2', models.PositiveIntegerField(blank=True, null=True)),
                ('nummer', models.PositiveIntegerField(blank=True, null=True)),
                ('tripletex', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gml_id', models.TextField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Extinguishant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrikat', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('lengde', models.CharField(blank=True, max_length=255, null=True)),
                ('slukkemiddel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasjon', models.CharField(max_length=255)),
                ('etg', models.SmallIntegerField()),
                ('plassering', models.CharField(max_length=255)),
                ('prodyear', models.PositiveSmallIntegerField()),
                ('sisteservice', models.DateField(blank=True, null=True)),
                ('sistekontroll', models.DateField(blank=True, null=True)),
                ('nesteservice', models.DateField(blank=True, null=True)),
                ('nestekontroll', models.DateField(blank=True, null=True)),
                ('avvik', models.BooleanField(default=False)),
                ('aktiv', models.BooleanField(default=True)),
                ('gml_kid', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Customer')),
                ('extinguishant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Extinguishant')),
            ],
        ),
        migrations.CreateModel(
            name='Slokketype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('intervall', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ObjTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrolldato', models.DateField(blank=True, null=True)),
                ('servicedato', models.DateField(blank=True, null=True)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('added', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('user', models.CharField(default='user', max_length=255)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('avvik', models.ManyToManyField(blank=True, to='backend.Avvik')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Customer')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Object')),
                ('utbedret_avvik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utbedretavvik_avvik', to='backend.Avvik')),
            ],
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='slokketype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Slokketype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Month'),
        ),
        migrations.AddField(
            model_name='avvik',
            name='slokketype',
            field=models.ManyToManyField(to='backend.Slokketype'),
        ),
    ]
