# Generated by Django 3.0.4 on 2020-03-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200327_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
