# Generated by Django 3.0.4 on 2020-04-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekter', to='backend.Customer'),
        ),
    ]
