# Generated by Django 3.0.4 on 2020-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireCtrl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='month',
            name='sorting_number',
            field=models.IntegerField(default=None),
        ),
    ]
