# Generated by Django 3.0.4 on 2020-03-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireCtrl_app', '0003_auto_20200319_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde', models.CharField(max_length=255)),
                ('kundeinformasjon', models.CharField(blank=True, max_length=255, null=True)),
                ('badresse', models.CharField(blank=True, max_length=255, null=True)),
                ('bpostnr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bpoststed', models.CharField(blank=True, max_length=255, null=True)),
                ('fadresse', models.CharField(blank=True, max_length=255, null=True)),
                ('fpostnr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fpoststed', models.CharField(blank=True, max_length=255, null=True)),
                ('kontaktperson', models.CharField(blank=True, max_length=255, null=True)),
                ('tlf1', models.PositiveIntegerField(blank=True, null=True)),
                ('tlf2', models.PositiveIntegerField(blank=True, null=True)),
                ('nummer', models.PositiveIntegerField(blank=True, null=True)),
                ('tripletex', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gml_id', models.TextField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireCtrl_app.Month')),
            ],
        ),
    ]
