# Generated by Django 3.0.4 on 2020-03-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireCtrl_app', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extinguishant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrikat', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('lengde', models.CharField(blank=True, max_length=255, null=True)),
                ('slukkemiddel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slokketype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=255)),
                ('intervall', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasjon', models.CharField(max_length=255)),
                ('etg', models.SmallIntegerField()),
                ('plassering', models.CharField(max_length=255)),
                ('prodyear', models.PositiveSmallIntegerField()),
                ('sisteservice', models.DateField(blank=True, null=True)),
                ('sistekontroll', models.DateField(blank=True, null=True)),
                ('nesteservice', models.DateField(blank=True, null=True)),
                ('nestekontroll', models.DateField(blank=True, null=True)),
                ('avvik', models.BooleanField(default=False)),
                ('aktiv', models.BooleanField(default=True)),
                ('gml_kid', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireCtrl_app.Customer')),
                ('extinguishant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireCtrl_app.Extinguishant')),
            ],
        ),
        migrations.AddField(
            model_name='extinguishant',
            name='slokketype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireCtrl_app.Slokketype'),
        ),
    ]
